Full support for all async iterables/iterators as inputs and sources (even if they don't have an `aclose()`)
andersea/slurry pull request #19
Opened 2024-02-08 04:55 UTC by mikenerone

In `_utils.py`, this branch provides `safe_closing()` (only meant for Slurry's use, so no doc changes). It can be used in place of the `async_generator.aclosing()` context manager that was used frequently previously, with two differences that make it safer:
1. It now works with any async iterable. Previously, it would error on one that didn't act as its own async iterator object. Granted, this is unusual, but taking the care makes type checkers happy.
2. It now works with any async iterator. Previously, it would error on one that didn't have an `aclose()` method, which is only _somewhat_ unusual.

Also provided is a `safe_aclose()` async function intended to be used anywhere an explicit `aclose()` method call is desired, but with the benefit of item 2 above, so that it's safe to use without checking for the presence of `aclose()`.

All of the input async gens that previously lived in `tests/fixtures.py` are now set up as actual pytest fixtures (in `tests/conftest.py`). This allows them to yield both "with `aclose()`" and "without `aclose()`" versions of themselves so that all existing tests that use them (with a small signature update) automatically generate tests for both cases (test count went from 43 to 76 to cover all these cases).

As a result of using `safe_closing()` everywhere, the `async_generator` dependency is not longer needed, and has been removed.

2024-02-15 21:05 UTC, andersea commented
Thanks for this. Haven't had time to do anything but a superficial look over the first couple of changes. The changes look ok so far. Hopefully I can get a moment to go through everything this weekend.

2024-03-08 19:40 UTC, andersea requested changes
Going through this was quite a bit more challenging than I anticipated. I have never used test fixtures in pytest, so it was a lot to wrap my head around. Took a bit headscratching and some research to figure out. I wonder if maybe the same could be achieved with a simpler approach than creating a custom fixture function wrapper?

The other main comment is, that there seems to be some test code that is now redundant, because of the new fixtures, which could be removed. See the comments on the individual files.

2024-03-08 19:40 UTC, andersea commented on tests/test_filters.py
Testing Skip with AsyncNonIteratorIterable doesn't actually test anything, unless I am mistaken, somehow. The Skip section is written now so that it explicitly gets a iterator for the iterable, and no longer assumes that the Iterable is its own iterator. Therefore there is no possible way for this test to fail.

2024-03-08 19:40 UTC, andersea commented on tests/test_pipeline.py
Looks like the import of AsyncIteratorWithoutAclose is a remnant from an earlier version, which is no longer needed, since this is handled by conftest now.

2024-03-08 19:40 UTC, andersea commented on tests/test_threading.py
Here also, testing with AsyncNonIteratorIterable does nothing. The test supposedly checks the entire pipeline machinery end to end for correct usage of Iterable/Iterator, but the only place iteration is happening outside of individual sections is in the pipeline pump function, which uses the async for mechanism, that does not assume anything other than the object being an async iterable.

2024-03-08 19:40 UTC, andersea commented on tests/fixtures.py
As noted in several other comments the inclusion of both AsyncNonIteratorIterable and AsyncIteratorWithoutAclose is not necessary since the test is either redundant or already included in conftest.py. Both of these can be removed from here and the dependancies eliminated.

2024-03-16 02:35 UTC, mikenerone commented on tests/test_filters.py
Well, yes, in Skip's current form (with the behavior you described), this test will always pass, but it's _always_ the case that a test always passes for its subject in its current form (else you wouldn't release it :D). The purpose of the test is to ensure it _still_ passes when changed in the future. Someone could change the `Skip` implementation, changing the behavior you described, potentially causing this test to fail.

While I don't agree that _this_ test is superfluous, I'd also argue that even if there _was_ such a case, it would usually require some deeper, and more error-prone, thinking to realize that that's the case, so even then the test has value because we can _know_ the case is handled without that risk. It's also just plain easier to use the adaptive fixture consistently.

2024-03-16 02:38 UTC, mikenerone commented on tests/test_threading.py
Correct, indeed! Fixed!

2024-03-16 02:39 UTC, mikenerone commented on tests/test_pipeline.py
Correct, indeed! Fixed!

2024-03-16 02:42 UTC, mikenerone commented on tests/test_threading.py
I believe my [reasoning from the other comment](https://github.com/andersea/slurry/pull/19#discussion_r1527022594) applies.

2024-03-16 02:54 UTC, mikenerone commented on tests/fixtures.py
Regarding `AsyncNonIteratorIterable`, I'll await your reply to [my previous reasoning](https://github.com/andersea/slurry/pull/19#discussion_r1527022594), but you're absolutely right about the redundant copy of that `AsyncIteratorWithoutAclose` class. Fixed! I removed the one in `conftest.py` and kept the one in `fixtures.py` to keep it where it's more potentially reusable (though that may never be necessary due to the pytest fixtures in `conftest.py`).

2024-03-16 03:00 UTC, mikenerone commented
> Going through this was quite a bit more challenging than I anticipated. I have never used test fixtures in pytest, so it was a lot to wrap my head around. Took a bit headscratching and some research to figure out. I wonder if maybe the same could be achieved with a simpler approach than creating a custom fixture function wrapper?

I appreciate you putting in the time! To answer your question, the other approach would be to duplicate all of the tests to cover both cases separately. While that's "simpler" in some way, it's a maintainability trade-off because it's much less DRY, the risk being that when making a test update, one misses one of the two places. IMO maintainability and consistency should be the overriding concerns, but I'll of course defer to your wishes if you prefer the explicitly duplicated tests.

2024-04-16 18:27 UTC, merged

2024-04-16 18:27 UTC, andersea commented
Merged! Thanks!

And sorry for the extremely long delay! I went to Texas for the eclipse for two weeks and just came back this weekend and before that, prep for travel and work took up all my time.

2024-04-19 16:48 UTC, mikenerone commented
> Merged! Thanks!
> 
> And sorry for the extremely long delay! I went to Texas for the eclipse for two weeks and just came back this weekend and before that, prep for travel and work took up all my time.

Hehe, no worries. I was also in Texas (where I live) for the eclipse. Hadn't seen a cloud for three months prior. Suddenly overcast that day.